RetailGuruEnterprises/Controllers/EmployeeProfileViewModelController.cs
using DatabaseAccess;
using RetailGuruEnterprises.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace RetailGuruEnterprises.Controllers
{
    public class EmployeeProfileViewModelController : Controller
    {
        private RetailGuruEntities db = new RetailGuruEntities();
        // GET: EmployeeProfileViewModel
    
        public ActionResult profilecheck(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var employee = db.EmployeeTables.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }

            var educationDetails = db.EmployeeEducationTables.Where(e => e.EmployeeID == id).ToList();
            var salaryDetails = db.EmployeeSalaryTables.Where(e => e.EmployeeID == id).ToList();

            var viewModel = new EmployeeProfileViewModel
            {
                Employee = employee,
                EducationDetails = educationDetails,
                SalaryDetails = salaryDetails
            };



            return View(viewModel);
        }

    }
}

RetailGuruEnterprises/Controllers/EmployeeTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DatabaseAccess;

namespace RetailGuruEnterprises.Controllers
{
    public class EmployeeTablesController : Controller
    {
        private RetailGuruEntities db = new RetailGuruEntities();

        // GET: EmployeeTables
        public ActionResult Index()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            var employeeTables = db.EmployeeTables.Include(e => e.DesignationTable).Include(e => e.UserTable);
            return View(employeeTables.ToList());
        }

        // GET: EmployeeTables/Details/5
        public ActionResult Details(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeTable employeeTable = db.EmployeeTables.Find(id);
            if (employeeTable == null)
            {
                return HttpNotFound();
            }
            return View(employeeTable);
        }

        // GET: EmployeeTables/Create
        public ActionResult Create()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            ViewBag.Designation_ID = new SelectList(db.DesignationTables, "DesignationID", "Title");
            ViewBag.User_ID = new SelectList(db.UserTables, "UserID", "FullName");
            return View();
        }

        // POST: EmployeeTables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmployeeTable employeeTable)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }


            int userid = Convert.ToInt32(Convert.ToString(Session["UserID"]));
            employeeTable.User_ID = userid;


            employeeTable.Photo = "/Content/EmployeePhotos/default.png";
            if (ModelState.IsValid)
            {
                db.EmployeeTables.Add(employeeTable);
                db.SaveChanges();

                if (employeeTable.PhotoFile != null)
                {
                    var folder = "/Content/EmployeePhotos";
                    var file = string.Format("{0}.png", employeeTable.EmployeeID);
                    var response = FileHelper.UploadFile.UploadPhoto(employeeTable.PhotoFile, folder, file);

                    if (response)
                    {
                        var pic = string.Format("{0}/{1}", folder, file);
                        employeeTable.Photo = pic;
                        db.Entry(employeeTable).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                }

                return RedirectToAction("Index");
            }


            ViewBag.Designation_ID = new SelectList(db.DesignationTables, "DesignationID", "Title", employeeTable.Designation_ID);
            ViewBag.User_ID = new SelectList(db.UserTables, "UserID", "FullName", employeeTable.User_ID);
            return View(employeeTable);
        }

        // GET: EmployeeTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeTable employeeTable = db.EmployeeTables.Find(id);
            if (employeeTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.Designation_ID = new SelectList(db.DesignationTables, "DesignationID", "Title", employeeTable.Designation_ID);
            ViewBag.User_ID = new SelectList(db.UserTables, "UserID", "FullName", employeeTable.User_ID);
            return View(employeeTable);
        }

        // POST: EmployeeTables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EmployeeTable employeeTable)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            if (ModelState.IsValid)
            {
                if (employeeTable.PhotoFile != null)
                {
                    UploadEmployeePhoto(employeeTable);
                }

                db.Entry(employeeTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Designation_ID = new SelectList(db.DesignationTables, "DesignationID", "Title", employeeTable.Designation_ID);
            ViewBag.User_ID = new SelectList(db.UserTables, "UserID", "FullName", employeeTable.User_ID);
            return View(employeeTable);
        }
        // GET: EmployeeTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EmployeeTable employeeTable = db.EmployeeTables.Find(id);
            if (employeeTable == null)
            {
                return HttpNotFound();
            }
            return View(employeeTable);
        }

        // POST: EmployeeTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            EmployeeTable employeeTable = db.EmployeeTables.Find(id);
            db.EmployeeTables.Remove(employeeTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        private bool UploadEmployeePhoto(EmployeeTable employeeTable)
        {
            var folder = "/Content/EmployeePhotos";
            var file = string.Format("{0}.png", employeeTable.EmployeeID);
            var response = FileHelper.UploadFile.UploadPhoto(employeeTable.PhotoFile, folder, file);

            if (response)
            {
                var pic = string.Format("{0}/{1}", folder, file);
                employeeTable.Photo = pic;
                return true;
            }

            return false;
        }
    }
}

RetailGuruEnterprises/Controllers/ReportsController.cs
using DatabaseAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RetailGuruEnterprises.Controllers
{
    public class ReportsController : Controller
    {
        private RetailGuruEntities db = new RetailGuruEntities();
        // GET: Reports
        public ActionResult EmployeeAttendance(int? id)
        {
            var staffattendance = db.EmployeeAttendanceTables.Where(t => t.Employee_ID == id).OrderByDescending(t => t.EmployeeAttendanceID);
            return View(staffattendance);
        }

        public ActionResult EmployeePerformance(int? id)
        {
            var empperformance = db.EmployeePerformances.Where(t => t.EmployeeID == id).OrderByDescending(t => t.PerformanceID);
            return View(empperformance);
        }


        //[HttpPost]
        //public ActionResult profilecheck(int? id)
        //{
           
        //    var empideducation = db.EmployeeEducationTables.Find(id);
        //    var empidsalary = db.EmployeeSalaryTables.Find(id);
        //    var empidemptbl = db.EmployeeTables.Find(id);
        //    if (empideducation != null && empidsalary != null && empidemptbl != null)
        //    {
        //        var emptables = db.EmployeeTables.Where(e => e.EmployeeID == empidemptbl.EmployeeID).ToList();
      
        //        return View(emptables);
        //    }
        //    if (empideducation != null && empidsalary != null && empidemptbl != null)
        //    {
        //        var empeducation = db.EmployeeEducationTables.Where(e => e.EmployeeID == empideducation.EmployeeID).ToList();

        //        return View(empeducation);
        //    }
        //    if (empideducation != null && empidsalary != null && empidemptbl != null)
        //    {
        //        var empsalary = db.EmployeeSalaryTables.Where(e => e.EmployeeID == empidsalary.EmployeeID).ToList();

        //        return View(empsalary);
        //    }
        //    return HttpNotFound();
        //}
    }
}

RetailGuruEnterprises/Views/EmployeeTables/Create.cshtml
@model DatabaseAccess.EmployeeTable

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<div class="card mb-4 shadow">
    <div class="card-header">
        Employee Information
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Create", "EmployeeTables", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>EmployeeTable</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Designation_ID, "Designation_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Designation_ID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Designation_ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Qualification, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Qualification, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Qualification, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhotoFile, "Select Photo", htmlAttributes: new { @class = "control-label" })
                    <span class="btn btn-default btn-file">
                        @Html.TextBoxFor(model => model.PhotoFile, new { type = "file", @class = "form-control-file" })
                    </span>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

RetailGuruEnterprises/Views/EmployeeTables/Delete.cshtml
@model DatabaseAccess.EmployeeTable

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EmployeeTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qualification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qualification)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DesignationTable.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DesignationTable.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserTable.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserTable.FullName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RetailGuruEnterprises/Views/EmployeeTables/Details.cshtml
@model DatabaseAccess.EmployeeTable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>EmployeeTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Qualification)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Qualification)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DesignationTable.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DesignationTable.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserTable.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserTable.FullName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EmployeeID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RetailGuruEnterprises/Views/EmployeeTables/Edit.cshtml
@model DatabaseAccess.EmployeeTable

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div class="card mb-4 shadow">
    <div class="card-header">
        Employee Information
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Edit", "EmployeeTables", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>EmployeeTable</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.EmployeeID)

                <div class="form-group">
                    @Html.LabelFor(model => model.User_ID, "User_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("User_ID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.User_ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Designation_ID, "Designation_ID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Designation_ID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Designation_ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Qualification, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Qualification, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Qualification, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PhotoFile, "Select Photo", htmlAttributes: new { @class = "control-label" })
                    <span class="btn btn-default btn-file">
                        @Html.TextBoxFor(model => model.PhotoFile, new { type = "file", @class = "form-control-file" })
                    </span>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

RetailGuruEnterprises/Views/EmployeeTables/Index.cshtml
@model IEnumerable<DatabaseAccess.EmployeeTable>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DesignationTable.Title)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ContactNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailAddress)
            </td>
            <td>
                @if (!string.IsNullOrEmpty(item.Photo))
                {
                    <img src="@Url.Content(item.Photo)" alt="Image" style="width:100px;height:150px;max-width:100%;height:auto;" />
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DesignationTable.Title)
            </td>
            <td>
                @Html.ActionLink("Attendance Report", "EmployeeAttendance", "Reports", new { id = item.EmployeeID }, null) |
                @Html.ActionLink("Performances", "EmployeePerformance", "Reports", new { id = item.EmployeeID }, null) |
                @Html.ActionLink("profile check", "profilecheck", "EmployeeProfileViewModel", new { id = item.EmployeeID }, null) |
                @Html.ActionLink("Edit", "Edit", new { id = item.EmployeeID }) |
                @Html.ActionLink("Details", "Details", new { id = item.EmployeeID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.EmployeeID })
            </td>
        </tr>
    }

</table>